[project]
name = "stacks-donation-tracker"
description = "A transparent donation tracking dApp on Stacks blockchain"
authors = ["Stacks Developer"]
telemetry = false
cache_dir = "./.clarinet"

[network]
testnet = "https://stacks-node-api.testnet.stacks.co"
mainnet = "https://stacks-node-api.mainnet.stacks.co"

[[project.requirements]]
contract_id = "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard"

[contracts.donation-tracker]
path = "contracts/donation-tracker.clar"
depends_on = []

[contracts.donation-rewards]
path = "contracts/donation-rewards.clar"
depends_on = ["donation-tracker"]

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
